### ISSUE TITLE
GPU utilization is low and training is extremely slow

### ISSUE THREAD

**Issue by JiangZQYW** [TachibanaYoshino/AnimeGAN#50]
I installed tf-gpu 1.15.0, my GPU utilization is about 20%, an iter will run for 10s, and a data set will run for about 13 days

**Comment by JiangZQYW** [comment]
The problem has been resolved. My computer only has a 2080ti, and in main.py
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

Change it to
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
